# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask-password-generator.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "flask-password-generator.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "flask-password-generator.fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"   # Request 64 MiB of memory
            cpu: "100m"      # Request 100 millicores (0.1 CPU)
          limits:
            memory: "128Mi"  # Limit memory usage to 128 MiB
            cpu: "200m"      # Limit CPU usage to 200 millicores (0.2 CPU)
