apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-password-generator
spec:
  replicas: 3  # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: flask-password-generator
  template:
    metadata:
      labels:
        app: flask-password-generator
    spec:
      containers:
      - name: flask-password-generator
        image: jmuachifi/passgen:v2.0 # Update with your Docker image
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-password-generator
spec:
  selector:
    app: flask-password-generator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-password-generator-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: your domain here   # Update with your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-password-generator
            port:
              number: 80
